### PR TITLE
New logo :tada: 

### PR DESCRIPTION
**Pull request by martinhoyer**
Adding files from https://gitlab.com/fedora/design/team/requests/-/issues/50 

Huge thanks to Maria and Fedora Design Team. I've added attribution and license to logo/README.md as per https://gitlab.com/fedora/design/team/requests/ license.

Favicon .ico was overwritten
The old logo files were moved to `/.old_logo/`

In tmt docs, we can add padding. This is 
```
.logo {
    padding: 10px 50px !important;
}
```
in `docs/tmt-custom.css` (10px top+bottom, 50px sides):
image

### CODE REVIEW

**Comment by martinhoyer** [comment]
Adding a version for dark backgrounds. Thanks Maria!
image

**Comment by martinhoyer** [comment]
@psss Pretty please :)

**Comment by psss** [comment]
Could we just move the old files under a `logo/old` directory? And do not rename them? Or could you explain what is the motivation for the leading underscores?

**Comment by psss** [comment]
A couple questions:

* Is the `tmt-logo-colors.png` file needed?
* What does `-f` mean in the file names?
* What is the difference between `tmt-logo-color-text-name.svg` and `tmt-logo-color-text-vertf`?

**Comment by martinhoyer** [comment]
> Could we just move the old files under a `logo/old` directory? And do not rename them? Or could you explain what is the motivation for the leading underscores?

Didn't thought to much about it. I suppose logo/old make sense. Or just delete it?

> A couple questions:
> 
>     Is the tmt-logo-colors.png file needed?

hmm, good point. I think it could be useful when pointing people to tmt colour scheme, but I guess the svg can do that job. Will remove.

>     What does -f mean in the file names?

Ha, I actually don't know, but assumed it has some meaning, like 'final' or something and didn't want to change it.  
Now I'm looking at it now, I don't see any pattern. Let me ask Maria and rename things as needed

>     What is the difference between tmt-logo-color-text-name.svg and tmt-logo-color-text-vertf?

Diff says they are identical, thanks.

**Comment by psss** [comment]
> Didn't thought to much about it. I suppose logo/old make sense. Or just delete it?

Let's keep them for now, under `old`, with the original names.

> hmm, good point. I think it could be useful when pointing people to tmt colour scheme, but I guess the svg can do that job. Will remove.

Ack.

> Ha, I actually don't know, but assumed it has some meaning, like 'final' or something and didn't want to change it.

I guess we can choose whatever names which suit our need. I would just avoid abbreviations to make the meaning straightforward at the first sight.

**Comment by martinhoyer** [comment]
@psss How does it look now?

**Review by psss — APPROVED** [review]
Nice, thanks!

**Comment by abitrolly** [comment]
From https://gitlab.com/fedora/design/team/requests/-/issues/50

> The current logo was not created by experienced designer 

What a bad way to evaluate the design. This

image

is awesome. No matter who've created it.

**Pull request merged**
